#!/bin/bash

filename="puppetlabs-release-$(lsb_release -sc).deb"
wget http://apt.puppetlabs.com/${filename}
dpkg -i ${filename}
apt-get update
apt-get -y install puppet-common

echo "Done" > /tmp/ccdone.flag
